### ISSUE TITLE
how can I find pretrained model?

### ISSUE THREAD

**Issue by Greatest-Marx** [ecker-lab/TreeLearn#1]
Thank you and your team for your contribution! I didn't find the pre-training model in the project you posted, can you please tell me where I can find the pre-training model: hais_ckpt_spconv2.pth

**Comment by JanvDelden** [comment]
Hello Greatest-Marx, 

The checkpoint is available from the [SoftGroup repository](https://github.com/thangvubk/SoftGroup#training). Please follow the link to the model denoted as „Converted hais checkpoint“. We are still working on cleaning up our documentation and code to make things easier to find.

**Comment by Greatest-Marx** [comment]
> Hello Greatest-Marx,
> 
> The checkpoint is available from the [SoftGroup repository](https://github.com/thangvubk/SoftGroup#training). Please follow the link to the model denoted as „Converted hais checkpoint“. We are still working on cleaning up our documentation and code to make things easier to find.

Thank you for your reply! I will download the pre-trained model as you instructed. In addition, I am now a sophomore student at China University of Geosciences (Wuhan), currently working on deep learning-based individual tree segmentation direction, if possible very much want to communicate with you about this direction, thank you!

**Comment by JanvDelden** [comment]
Thanks for your interest! Please feel free to reach out to us via the mail addresses provided in the paper.
