### ISSUE TITLE
Segmentation pipeline ends the process immediately.

### ISSUE THREAD

**Issue by Knutchanat** [ecker-lab/TreeLearn#11]
Hello, dear ecker-lab.
I try to run segmentation pipeline.
'python tools/pipeline/pipeline.py --config configs/pipeline/pipeline.yaml'

But when generating tiles step start, it ends the process immediately.

![Screenshot 2024-10-27 155805](https://github.com/user-attachments/assets/de025996-3389-462c-8989-5647e4ec64b3)

It's so confuse. What I do wrong.

**Comment by jonaden94** [comment]
It looks like you are running the pipeline on your personal computer, which might not have enough RAM to support the running of the pipeline. I suggest running the pipeline on a smaller plot or using a compute cluster.

**Comment by Knutchanat** [comment]
I think, I have enough RAM and storage for running the pipeline.
![image](https://github.com/user-attachments/assets/5d66f0db-8366-4df0-ba60-3e651e7c8369)

![image](https://github.com/user-attachments/assets/f6365153-8b22-4a04-9ac4-88888fcac65f)

**Comment by jonaden94** [comment]
Without any error messages, I cannot assess where the error might come from. We also never ran the pipeline on a Windows machine. So we do not have any experience there as well. All I can recommend is to debug it yourself. According to your log, the error happens somewhere in the "generate_tiles" function [here](https://github.com/ecker-lab/TreeLearn/blob/main/tree_learn/util/pipeline.py) below "logger.info('voxelizing forest...')"

**Comment by Knutchanat** [comment]
Because it not have any error messages, it make me so confuse. what's wrong with that. Thank you for your advice. your project is so incredible. It might helpful in my project.

**Comment by Knutchanat** [comment]
I switched from running the code on Windows machine to using Jupyter Notebook, where I discovered the issue. The error message 'The kernel for ipynb appears to have died' was occurring because Open3D wasn't working properly. I've now fixed the problem.
