### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by aaaaasleep** [ecker-lab/TreeLearn#2]
File "D:\anaconda3\envs\treelearn\lib\site-packages\spconv\pytorch\__init__.py", line 7, in <module>
    from spconv.pytorch.core import SparseConvTensor
  File "D:\anaconda3\envs\treelearn\lib\site-packages\spconv\pytorch\core.py", line 21, in <module>
    from spconv.tools import CUDAKernelTimer
  File "D:\anaconda3\envs\treelearn\lib\site-packages\spconv\tools.py", line 16, in <module>
    from spconv.cppconstants import CPU_ONLY_BUILD
  File "D:\anaconda3\envs\treelearn\lib\site-packages\spconv\cppconstants.py", line 15, in <module>
    import spconv.core_cc as _ext
ImportError: DLL load failed while importing core_cc: The specified module could not be found
How to solve this error?

**Comment by JanvDelden** [comment]
It seems like you are trying to install the cpu only version of spconv? Our code is only written for supporting the cuda version. Please make sure that you have a cuda-capable gpu on your system and that the nvidia drivers and cuda are correctly installed.

**Comment by aaaaasleep** [comment]
python tools/pipeline/pipeline.py --config configs/pipeline/pipeline.yaml
I'm running this code, spconv-102 exists in the environment, reinstalled the environment and also this error is reported，cuda version is 10.2

**Comment by JanvDelden** [comment]
Please excuse the long waiting time for our answer. This seems to be an issue with installing spconv. Please reach out to the maintainers of spconv for support with this (https://github.com/traveller59/spconv). In general, we can only provide support running TreeLearn on Linux systems and not windows (as you seem to be using), as we only ever tested it on linux systems.
