### ISSUE TITLE
Colab notebook issue with paths

### ISSUE THREAD

**Issue by GabijaBern** [ecker-lab/TreeLearn#3]
Hello, Colab notebook fails with the following error: `'/usr/users/henrich1/TreeLearn/work_dirs/train/epoch_1180.pth'`. I think some path fixing is needed :)

**Comment by GabijaBern** [comment]
Also, related to this, where could I get the model needed for the segmentation? Can't seem to find the `*.pth` @JanvDelden @jonaden94 . I assume the latest versions are [here](https://data.goettingen-research-online.de/dataset.xhtml?persistentId=doi:10.25625/VPMPID)?

**Comment by GabijaBern** [comment]
@jonaden94

**Comment by JanvDelden** [comment]
We just updated the google colab notebook and repository, and would expect it to work now. The new and best model weights are available from https://data.goettingen-research-online.de/file.xhtml?persistentId=doi:10.25625/VPMPID/1JMEQV&version=4.0. Alternatively, you can download them using the python command given in the Readme: python tree_learn/util/download.py --dataset_name model_weights_diverse_training_data --root_folder data/model_weights

Please let us know, if there are still issues.

**Comment by aornugent** [comment]
Hi - I'm not able to download the latest checkpoints. The goettingen-research-online website resets after 25%. Are there any mirrors?
