### ISSUE TITLE
How can I visualize the training results.

### ISSUE THREAD

**Issue by yongmanlove** [ecker-lab/TreeLearn#9]
I didn't see any visualization tools in this project. May I ask if the author has any visualization methods.

**Comment by JanvDelden** [comment]
Hello, 

to visualize point clouds, we recommend using the open source software CloudCompare (https://www.danielgm.net/cc/).

**Comment by yongmanlove** [comment]
thank you，  
how can i solve this problem  
![截图 2024-09-29 10-59-07](https://github.com/user-attachments/assets/ead7b308-c614-4cbc-be8a-b58a412c7d3e)

**Comment by yongmanlove** [comment]
config dont  change, pipline  to exe L1W will like this.

**Comment by yongmanlove** [comment]
I run pipline to execute code according to the default configuration, but it always kills. May I ask if the author has any suggestions for parameter adjustment. Look forward to your reply

**Comment by jonaden94** [comment]
This is most likely a RAM issue. See issue #6 for how to handle this.
